import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Info, AlertCircle, RotateCcw } from 'lucide-react';

interface ResultSectionProps {
  result: string;
  onReset: () => void;
}

const ResultSection: React.FC<ResultSectionProps> = ({ result, onReset }) => {
  return (
    <div className="animate-in slide-in-from-bottom-4 duration-500">
      <div className="bg-white rounded-2xl shadow-lg border border-slate-100 overflow-hidden">

        <div className="bg-medical-50 px-6 py-4 border-b border-medical-100 flex items-center justify-between">
          <div className="flex items-center gap-2 text-medical-800">
            <Info size={20} />
            <h3 className="font-semibold">Report Explanation</h3>
          </div>

          <button
            onClick={onReset}
            className="text-sm text-medical-600 hover:text-medical-800 flex items-center gap-1 font-medium transition-colors"
          >
            <RotateCcw size={14} />
            Analyze Another
          </button>
        </div>

        <div className="p-6 md:p-8 overflow-x-auto">
          <article className="markdown-prose">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{

                h1: ({node, ...props}) => (
                  <h1
                    className="text-xl font-bold text-slate-800 border-b border-slate-100 pb-2 mb-4 mt-6 first:mt-0"
                    {...props}
                  />
                ),

                h2: ({node, children, ...props}) => {
                  const text = String(children);

                  let headingClass =
                    "text-lg font-semibold mt-5 mb-3 px-4 py-3 rounded-xl";

                  if (
                    text.includes("🟢") ||
                    text.toLowerCase().includes("normal")
                  ) {
                    headingClass +=
                      " bg-green-100 text-green-700 border border-green-200";
                  } else if (
                    text.includes("🟡") ||
                    text.toLowerCase().includes("borderline")
                  ) {
                    headingClass +=
                      " bg-yellow-100 text-yellow-700 border border-yellow-200";
                  } else if (
                    text.includes("🔴") ||
                    text.toLowerCase().includes("attention")
                  ) {
                    headingClass +=
                      " bg-red-100 text-red-700 border border-red-200";
                  } else {
                    headingClass += " text-medical-700";
                  }

                  return (
                    <h2
                      className={headingClass}
                      {...props}
                    >
                      {children}
                    </h2>
                  );
                },

                p: ({node, ...props}) => (
                  <p
                    className="mb-4 text-slate-600 leading-relaxed"
                    {...props}
                  />
                ),

                li: ({node, ...props}) => (
                  <li
                    className="ml-4 list-disc marker:text-medical-400 pl-1 mb-2 text-slate-600"
                    {...props}
                  />
                ),

                strong: ({node, ...props}) => (
                  <strong
                    className="font-semibold text-slate-800"
                    {...props}
                  />
                ),

                table: ({node, ...props}) => (
                  <table
                    className="w-full border-collapse border border-slate-300 my-4 text-sm"
                    {...props}
                  />
                ),

                thead: ({node, ...props}) => (
                  <thead
                    className="bg-slate-100"
                    {...props}
                  />
                ),

                th: ({node, ...props}) => (
                  <th
                    className="border border-slate-300 px-3 py-2 text-left font-semibold"
                    {...props}
                  />
                ),

                td: ({node, ...props}) => (
                  <td
                    className="border border-slate-300 px-3 py-2"
                    {...props}
                  />
                ),
              }}
            >
              {result}
            </ReactMarkdown>
          </article>
        </div>

        <div className="bg-amber-50 p-4 border-t border-amber-100 flex gap-3">
          <AlertCircle className="text-amber-500 shrink-0" size={20} />

          <p className="text-sm text-amber-800">
            <strong>Reminder:</strong> This explanation is generated by AI for informational purposes only.
            It is not a medical diagnosis. Always discuss your results with your doctor.
          </p>
        </div>

      </div>
    </div>
  );
};

export default ResultSection;
